; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\Arduino-LiquidCrystal-I2C-library-master.zip
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\mpu6050-master.zip
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\pubsubclient-master.zip
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\Adafruit_BMP280_Library-master.zip
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\ArduinoJson-7.x.zip
	D:\RTOS-Based-Smart-Multi-Sensor-Data-Logger\Supportive\Required Library\Arduino-MAX30100-master.zip
build_flags =
    -mlongcalls
    -Wl,--gc-sections